### ISSUE TITLE
System.BadImageFormatException / System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by andreaPorini** [DigitalFlow/Xrm-Templating-Language#15]
Hi DigitalFlow,

I have registered 2 step on PreCreate for the Xrm.Oss.XTL.Templating.XTLProcessor plugin but when I try to save the destination entity record I get one of the following two error message:

- System.BadImageFormatException
- System.IO.DirectoryNotFoundException

To try to solve the problem I tried the following things without success:

- Tried to create the record with no field populated
- Tried to create the record with all field populated
- Unregistered the plugin steps and re-registerd
- Tried to registed the steps on another entity
- Unistalled and re-installed the Xrm.Oss.Xrm-Templating-Language solution 
and re-tested all the points above 

Can you please help me?

Let me know if you need further information.

Regards,
Andrea

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

is it possible that you have some other plugins with early bindings running before the XTL plugins execute?
I think I already saw these exceptions on those cases.
This is due to the types not being available in the XTL assemblies, it seems as each plugin has to serialize and deserialize the target record.

If you really do have plugins with early bindings running before, you could try to not set the target as early bound object, but to use ToEntity<Entity>() when setting it in the context.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @andreaPorini,

did you solve your issues?

Kind Regards,
Florian

**Comment by andreaPorini** [comment]
Hi @DigitalFlow,

thanks for the feedback.

I confirm that the problem has been solved. 
There was one CWAs that caused the problem, in fact in another environment everything worked correctly.

Thanks again.

Kind Regards,
Andrea
